---
#- name: Install jmespath for JSON parsing
#  local_action:
#    module: pip
#    name: jmespath

- name: Install jq for JSON parsing
  package:
    name: jq
    state: latest
  register: installed_jq
  when: installed_jq is not defined

# Don't let Ansible fetch it as JSON, otherwise it'll do all sorts of random
# magic on it, messing up with parsing.
- name: Fetch latest release info
  uri:
    url: "https://api.github.com/repos/{{ owner }}/{{ repo }}/releases/{% if tag is defined and tag | length %}tags/{{ tag }}{% else %}latest{% endif %}"
    body_format: raw
    return_content: true
    headers:
      Authorization: "{% if github_token is defined and github_token | length %}Bearer {{ github_token }}{% else %}None{% endif %}"
  register: gh_rel

# Lovely JMESPath expression to extract asset URL for a certain prefix/suffix.
# Oh yes, gotta love that beautiful and trivial escaping <3
#- set_fact:
#    github_release_url: "{{ gh_rel.json | json_query('assets[? starts_with(name, `\"' + prefix + '\"`) && ends_with(name, `\"' + suffix + '\"`)].browser_download_url') | first }}"

# Make sure to use quota filter to avoid errors with releases where the body
# contains stuff like quotes, leading to errors like:
# unexpected EOF while looking for matching `''"
# Note that JSON *can* contain quotes, it's a Jinja2 issue.
- name: Find asset URL
  shell:
    cmd: "jq --raw-output -n '$input.assets[] | select(.name| startswith(\"{{ prefix }}\")) | select(.name|endswith(\"{{ suffix }}\")) | .browser_download_url' --argjson input {{ gh_rel.content | quote }}"
  changed_when: false
  register: json_filter

- set_fact:
    github_release:
      url: "{{ json_filter.stdout_lines | first }}"
